In [1]:
import torch

In [2]:
x = torch.arange(12)
print(x)
print('\n')
x = x.view(3, 4)
print(x)
print('\n')
x = x.transpose(0, 1)
print(x)
print('\n')
x = x.reshape(4, 3)
print(x)
print('\n')
x = x.unsqueeze(0)
print(x)
print('\n')
x = x.squeeze(0)
print(x)
print('\n')
x = x.t()
print(x)
print('\n')
x = x.permute(1, 0)
print(x)
print('\n')

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]]])


tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])




In [3]:
print(x)
print(x.shape)

x_transpose = x.transpose(0,1)
#transpose should be stored in a new variable
# to avoid modifying the original matrix!!

print(x_transpose)
print(x_transpose.shape)

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
torch.Size([4, 3])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [4]:
print(x.numel())
# numel is a shortcut for "number of elements"

zero_tensor = torch.zeros(2,3,4)
print(zero_tensor)

ones_tensor = torch.ones(2,3,4)
print(ones_tensor)

rand_tensor = torch.rand(2,3,4)
print(rand_tensor)
# the value of each element is randomly generated between 0 and 1
# according to the normal distribution(gaussian distribution)
# with mean 0 and standard deviation 1.

rand_int_tensor = torch.randint(0, 10, (2,3,4))
print(rand_int_tensor)
# the value of each element is randomly generated between 0 and 9
# according to the uniform distribution.

rand_normal_tensor = torch.randn(2,3,4)
print(rand_normal_tensor)
# the value of each element is randomly generated according to the normal distribution.
# with mean 0 and standard deviation 1.



12
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0.5274, 0.8478, 0.0938, 0.6643],
         [0.0314, 0.8992, 0.5968, 0.6658],
         [0.6058, 0.5595, 0.9993, 0.9564]],

        [[0.4817, 0.3176, 0.2421, 0.2171],
         [0.2114, 0.2285, 0.2035, 0.7274],
         [0.6379, 0.5188, 0.2084, 0.0966]]])
tensor([[[5, 4, 0, 4],
         [8, 5, 9, 6],
         [8, 5, 1, 1]],

        [[3, 6, 8, 7],
         [7, 8, 0, 4],
         [2, 2, 9, 4]]])
tensor([[[ 1.0446,  0.2303, -1.6450, -0.4448],
         [ 1.4014, -1.6944,  1.9327, -0.8819],
         [-1.4641, -0.0959, -2.5783,  2.0555]],

        [[ 0.6993,  0.2844, -0.4642, -2.2004],
         [-0.9252,  0.4960,  0.0253,  2.3199],
         [ 1.0825, -0.43

In [5]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

res = a + b
print(res)

res = a - b
print(res)

res = a * b
print(res)

res = a / b
print(res)

res = a**b
print(res)

res = a.dot(b)
print(res)

res = a.sum()
print(res)

res = a.exp()
print(res)

res = a.log()
print(res)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
tensor([  1,  32, 729])
tensor(32)
tensor(6)
tensor([ 2.7183,  7.3891, 20.0855])
tensor([0.0000, 0.6931, 1.0986])


In [6]:
a = torch.arange(12,dtype=torch.float32).reshape(3,4)
print(a)
print('\n')

b = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(b)
print('\n')

res = a + b
print(res)
print('\n')

ab_row = torch.cat((a,b),dim=0)
# catenate along row(keep the same column number)
# linked like this:
# ab_row = | a11 a12 a13 a14 |
#          | a21 a22 a23 a24 |
#          | a31 a32 a33 a34 |
#          -------------------
#          | b11 b12 b13 b14 |
#          | b21 b22 b23 b24 |  
#          | b31 b32 b33 b34 |

ab_col = torch.cat((a,b),dim=1)
# catenate along column(keep the same row number)
# linked like this:
# ab_col = | a11 a12 a13 a14 | b11 b12 b13 b14 |
#          | a21 a22 a23 a24 | b21 b22 b23 b24 |
#          | a31 a32 a33 a34 | b31 b32 b33 b34 |

print(ab_row)
print('\n')
print(ab_col)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])


tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [7]:
ab_compare = a == b
print(ab_compare)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


In [8]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)

print(a)
print(b)

print('\n')

res = a + b
# tensor with different shape
# would broadcast to the same shape when calculating

print(res)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [9]:
print(a)
a[0:2] = 3
print(a)

tensor([[0],
        [1],
        [2]])
tensor([[3],
        [3],
        [2]])


In [10]:
X = torch.tensor([1, 2, 3, 4, 5])
Y = torch.tensor([1, 2, 3, 4, 5])
Z = torch.zeros_like(Y)
print(Z)
print('id(Z):', id(Z))

Z[:] = X + Y
print(Z)
print('id(Z):', id(Z))

#code like this to avoid create new tensor every time
#so that we can use the same tensor to store the result
#avoid too many memory usage!!!

tensor([0, 0, 0, 0, 0])
id(Z): 1636308854288
tensor([ 2,  4,  6,  8, 10])
id(Z): 1636308854288


In [11]:
print(X)
print(type(X))
Y = X.numpy()
print(Y)
print(type(Y))

tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


## 小结

* 深度学习存储和操作数据的主要接口是张量（$n$维数组）。它提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换其他Python对象。