# Linear Algebra

In [434]:
import torch

x = torch.arange(4)

x

tensor([0, 1, 2, 3])

In [435]:
len(x)

4

In [436]:
x.shape

torch.Size([4])

In [437]:
A = torch.arange(20).reshape(5,4)
print(A)
print('\n')

B = A.T
print(B)
print('\n')

C = A @ B
print(C)
print('\n')

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


tensor([[  14,   38,   62,   86,  110],
        [  38,  126,  214,  302,  390],
        [  62,  214,  366,  518,  670],
        [  86,  302,  518,  734,  950],
        [ 110,  390,  670,  950, 1230]])




In [438]:
symmetric_matrix = torch.tensor([[1,2,3],[2,4,5],[3,5,6]])
print(symmetric_matrix)

print(symmetric_matrix.t() == symmetric_matrix)

tensor([[1, 2, 3],
        [2, 4, 5],
        [3, 5, 6]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


尽管单个向量的默认方向是$列向量$，但在表示表格数据集的矩阵中，<br>
将每个数据样本作为矩阵中的$行向量$更为常见。<br>
后面的章节将讲到这点，这种约定将支持常见的深度学习实践。

In [439]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()

A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

具体而言，[**两个矩阵的按元素乘法称为*Hadamard积*（Hadamard product）（数学符号$\odot$）**]。
对于矩阵$\mathbf{B} \in \mathbb{R}^{m \times n}$，
其中第$i$行和第$j$列的元素是$b_{ij}$。
矩阵$\mathbf{A}$（在 :eqref:`eq_matrix_def`中定义）和$\mathbf{B}$的Hadamard积为：
$$
\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
    a_{11}  b_{11} & a_{12}  b_{12} & \dots  & a_{1n}  b_{1n} \\
    a_{21}  b_{21} & a_{22}  b_{22} & \dots  & a_{2n}  b_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1}  b_{m1} & a_{m2}  b_{m2} & \dots  & a_{mn}  b_{mn}
\end{bmatrix}.
$$


In [440]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [441]:
a = 2
A = torch.arange(24,dtype=torch.float32).reshape(2,3,4)
A,A.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],
 
         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]),
 torch.Size([2, 3, 4]))

$Dimensionality Reduction(降维)$

In [442]:
x = torch.arange(12).reshape(2,2,3)
print(x,'\n\n',x.shape,'\n\n',x.sum(),'\n\n')

x_sum_axis0 = x.sum(axis=0)
print(x_sum_axis0,'\n\n',x_sum_axis0.shape,'\n\n')

x_sum_axis1 = x.sum(axis=1)
print(x_sum_axis1,'\n\n',x_sum_axis1.shape,'\n\n')

x_sum_axis2 = x.sum(axis=2)
print(x_sum_axis2,'\n\n',x_sum_axis2.shape,'\n\n')

x_sum_axis01 = x.sum(axis=(0,1))
print(x_sum_axis01,'\n\n',x_sum_axis01.shape,'\n\n')

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]]) 

 torch.Size([2, 2, 3]) 

 tensor(66) 


tensor([[ 6,  8, 10],
        [12, 14, 16]]) 

 torch.Size([2, 3]) 


tensor([[ 3,  5,  7],
        [15, 17, 19]]) 

 torch.Size([2, 3]) 


tensor([[ 3, 12],
        [21, 30]]) 

 torch.Size([2, 2]) 


tensor([18, 22, 26]) 

 torch.Size([3]) 




In [443]:
x = torch.arange(12).reshape(2,2,3)
print(x,'\n\n',x.shape,'\n\n',x.sum(),'\n\n')

# get sum without reducing the dimension
sum_x = x.sum(axis=0, keepdims = True)
print(sum_x)

sum_x = x.cumsum(axis=0)
print(sum_x)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]]) 

 torch.Size([2, 2, 3]) 

 tensor(66) 


tensor([[[ 6,  8, 10],
         [12, 14, 16]]])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  8, 10],
         [12, 14, 16]]])


In [444]:
u = torch.tensor([3.0, -4.0])

# L2 norm of a vector
# norm calculation must be done on a tensor with float or double data type
print(torch.norm(u))

# L1 norm of a vector
print(torch.norm(u, 1),' ',torch.sum(torch.abs(u)))

# Frobenius norm of a matrix
A = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(torch.norm(A))

tensor(5.)
tensor(7.)   tensor(7.)
tensor(5.4772)


### 范数和目标

在深度学习中，我们经常试图解决优化问题：
*最大化*分配给观测数据的概率;
*最小化*预测和真实观测之间的距离。
用向量表示物品（如单词、产品或新闻文章），以便最小化相似项目之间的距离，最大化不同项目之间的距离。
目标，或许是深度学习算法最重要的组成部分（除了数据），通常被表达为范数。


## 小结(Linear Algebra Review)

* 标量、向量、矩阵和张量是线性代数中的基本数学对象。
* 向量泛化自标量，矩阵泛化自向量。
* 标量、向量、矩阵和张量分别具有零、一、二和任意数量的轴。
* 一个张量可以通过`sum`和`mean`沿指定的轴降低维度。
* 两个矩阵的按元素乘法被称为他们的Hadamard积。它与矩阵乘法不同。
* 在深度学习中，我们经常使用范数，如$L_1$范数、$L_2$范数和Frobenius范数。
* 我们可以对标量、向量、矩阵和张量执行各种操作。